# Generated by Django 4.2.5 on 2023-10-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_created_time_task_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.task')),
            ],
        ),
    ]
